### ISSUE TITLE
[Bug]: Undo/redo doesn't work correctly in Vim mode

### ISSUE THREAD

**Issue by Aaron-Bopp** [chrisgrieser/obsidian-smarter-md-hotkeys#16] opened 2022-01-11 00:49 UTC
### Bug Description

This is a weird one, and might be out of your control. ctrl+z and ctrl+shift+z work correctly, but their equivalents in Vim do not.

### To Reproduce

1. Use command
![image](https://user-images.githubusercontent.com/48270139/148861561-58299b7c-7788-4b23-842b-6841b9eb1362.png)
2. Undo once, (redo does not work at this point)
![image](https://user-images.githubusercontent.com/48270139/148861603-c52d1379-294d-4b23-87cd-3619838813c0.png)
3. Undo again 
![image](https://user-images.githubusercontent.com/48270139/148861674-f23f02d3-d355-4745-909f-4ababc6a28d4.png)
4. Redo, and further redo's do not get past this point
![image](https://user-images.githubusercontent.com/48270139/148861704-c18fea68-8091-46c2-92e9-7a659f385400.png)

### Obsidian Version

0.13.19

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur?

- [X] Source (Edit)
- [X] Live Preview

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment] 2022-01-11 01:00
The plugin doesn't touch the undo commands in any way – when the undo works in Vim mode but not in normal mode, it's most likely a problem with vim mode (also, vim mode isn't fully supported in the new editor yet, so that's probably the cause.)

Since, as you correctly suspected this plugin is not the cause of the problem, I'll close this. 

I assume that as soon as vim fully works in the new editor, this issue will also be solved 🙂

**Closed by chrisgrieser** 2022-01-11 01:00 UTC
Labels: bug

**Comment by chrisgrieser** [comment] 2022-01-11 11:14
yep, seems to be an Obsidian vim mode issue: 

[Vim undo sometimes reverts back multiple steps - Bug reports - Obsidian Forum](https://forum.obsidian.md/t/vim-undo-sometimes-reverts-back-multiple-steps/30198)
