### ISSUE TITLE
Feature Request: Exclude block ID when applying hotkeys

### ISSUE THREAD

**Issue by wenlzhang** [chrisgrieser/obsidian-smarter-md-hotkeys#2] opened 2021-11-20 18:17 UTC
As an addition to the request at https://github.com/chrisgrieser/obsidian-smarter-md-hotkeys/issues/1, it would be great if block ID can be excluded when applying hotkeys to a selected line of text/list/task item.

For instance, the second one rather than the first one is desired:
```
- [ ] ==This is not desired. ^blockid==
- [ ] ==This is desired.== ^blockid
```

**Comment by chrisgrieser** [comment] 2021-11-20 18:39
fixed in the last release

**Comment by wenlzhang** [comment] 2021-11-20 18:55
It seems that the hotkeys are applied on the extra space before the block ID, which breaks the block link in preview mode.
```
- ~~The current effect ~~^blockid
- ~~The desired effect~~ ^blockid
```

**Comment by wenlzhang** [comment] 2021-11-20 19:01
It would be great if the following can also be fixed:
```
- This ==is actually not ==desired.
- This ==is actually desired== without the additional space being consideed.
```

**Comment by chrisgrieser** [comment] 2021-11-20 19:02
That's strange, when I do it, it seems to work? 🤔

https://user-images.githubusercontent.com/73286100/142738075-7a3a8bc4-a7d2-4859-b915-a671024721b0.mov

Maybe it's an issue with updating via BRAT? Could you reinstall the plugin? And if the issue still occurs, attach the markdown file you are ussing?

**Comment by chrisgrieser** [comment] 2021-11-20 19:03
> It would be great if the following can also be fixed:
> 
> ```
> - This ==is actually not ==desired.
> - This ==is actually desired== without the additional space being considered.
> ```

this one works for me, too. could you show with a screenshot what exactly you have selected before triggering the hotkey to get that result?

**Comment by wenlzhang** [comment] 2021-11-20 19:12
These two cases can be seen as follows:
![CleanShot 2021-11-20 at 20 10 38](https://user-images.githubusercontent.com/44930227/142738320-4844ed7c-75ab-4eaf-aab6-915e86ea9f3e.gif)

**Comment by chrisgrieser** [comment] 2021-11-20 21:45
okay, I got it, both are caused by a space being at the end of a multi-word-selection (which is why I didn't pick it up, since my example only had one word selected).

[Version 0.9.8](https://github.com/chrisgrieser/obsidian-smarter-md-hotkeys/releases/tag/0.9.8) should fix this!

**Closed by chrisgrieser** 2021-11-20 21:45 UTC
Labels: enhancement
