### ISSUE TITLE
[Bug]: Undo redo doesn't work inside tags 

### ISSUE THREAD

**Issue by Aaron-Bopp** [chrisgrieser/obsidian-smarter-md-hotkeys#14] opened 2022-01-11 00:31 UTC
### Bug Description

Noticed this while I was making the other issues, hopefully fixing this and implementing them will go hand in hand :D

### Relevant Screenshot

There is one use of the smarter bold command between each of these screenshots
![image](https://user-images.githubusercontent.com/48270139/148860168-3c11a077-191d-4cbd-9782-85f5ef07e277.png)
![image](https://user-images.githubusercontent.com/48270139/148860199-12815c42-5c3e-4840-90c8-ce3557b0b128.png)
![image](https://user-images.githubusercontent.com/48270139/148860218-e067a207-ec20-4ddb-9e6f-0c72b6462586.png)
![image](https://user-images.githubusercontent.com/48270139/148860303-e71e78fe-e5da-428e-b813-5840dcbc7c32.png)

### To Reproduce

1. Activate smarter bold command inside of a bolded tag
2. repeat

This was broken in normal and insert mode (of Vim) but I did not test with Vim mode off. It seemed to work fine on regular text, but I didn't test any other syntax

### Obsidian Version

0.13.19

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur?

- [X] Source (Edit)
- [X] Live Preview

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment] 2022-01-11 00:54
You cannot know it, but that one actually isn't a bug, but a duplicate of the feature request #15. :D

Reason being that you are trying to undo bold around a *nested* tag. it works fine for normal tags, but nested tags with the "/" around them are basically interpreted as multiple words by the function that expands to words (and in most cases this makes sense, e.g. "a red/blue shirt").

nested tags and multi-word wikilinks are both, however, much harder to implement, so that's something I cannot fix in few minutes like the other issues, but have to table for when I have more time.

Since both are actually the same issue, I'll close this one.

**Closed by chrisgrieser** 2022-01-11 00:54 UTC
Labels: duplicate, enhancement
