### ISSUE TITLE
[Bug]: Round/Curly brackets wrap wrong set of characters

### ISSUE THREAD

**Issue by dummifiedme** [chrisgrieser/obsidian-smarter-md-hotkeys#21] opened 2022-01-21 16:44 UTC
### Bug Description

I replaced my `(` with a smart shortcut `Shift + 9` (basically the same thing).
But there is an edge case where it is failing. 

`This is a function()`  is what I want to write.
`This is a (function)` is what I get.

Basically, whenever I wish to start a function (dataview and codeblocks mostly). I end up messing it up. 

If I was not able to get it clear, please reply, I will try again :D

Thanks for the plugin!!

### Obsidian Version

0.13.19

### Which editor are you using?

- [X] New Editor
- [X] Legacy Editor

### In which mode(s) does the problem occur?

- [X] Source (Edit)
- [ ] Live Preview

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment] 2022-02-02 16:34
Yeah, that's because the expansion mechanic expands to the full word. In a way, that is the intended behavior, actually.

I can see your thinking, but changing the behavior could be counterintuitive for people who are used to the fact that this plugin select the whole word, when the cursor is right next to a word. So I am not entirely sure whether I change/fix this, since it also covers quite an edge case: you would have to use smart punctuation as normal punctuation replacement, write in *codeblocks*, and then in code blocks at the edge of a word. 

You can however, circumvent the problem easily by writing adding a space after the word. since in that case it is clear do you do not want to add the brackets to the word: `function ()`

So to me, it looks like an edge case, where the current behavior can often be the preferred behavior, which can also easily be avoided by adding a space after the `function` (which is also considered good code writing practice by some). Hence I strongly tend to not change this, tbh. I'll close this for now, if more people voice their preference for the change you suggested, I'll reconsider.

**Closed by chrisgrieser** 2022-02-02 16:34 UTC
Labels: bug
